### ISSUE TITLE
Make it so you are able to add an option to bypass cooldowns with a permission, administrator, ban_members and so on

### ISSUE THREAD

**Issue by ghost** [Skelmis/Function-Cooldowns#7]
Well i'm trying to test my bot but there are 1.5k members on the server so I am afraid people are gonna start spammming with it if I turn off cooldown so if this could happen thank you

**Comment by Skelmis** [comment]
This is already possible using https://function-cooldowns.readthedocs.io/en/latest/modules/examples.html#cooldown-checks with a reference found here https://function-cooldowns.readthedocs.io/en/latest/modules/decorators.html#cooldowns.cooldown

Note: Cooldown checks are given the same arguments as the cooldown itself
